name: Release

on:
  push:
    tags:
      - "v*.*.*" # déclenche sur un tag de version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # adapte selon ton projet

      - name: Build binaries
        run: |
          mkdir -p dist
          for os in linux darwin windows; do
            for arch in amd64 arm64; do
              echo "Building for $os/$arch"
              GOOS=$os GOARCH=$arch go build -o dist/terraform-provider-${{ github.event.repository.name }}_${os}_${arch}
              zip dist/terraform-provider-${{ github.event.repository.name }}_${os}_${arch}.zip dist/terraform-provider-${{ github.event.repository.name }}_${os}_${arch}*
              rm dist/terraform-provider-${{ github.event.repository.name }}_${os}_${arch}
            done
          done

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > SHA256SUMS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}   # <-- utiliser ton PAT ici
