name: Release

on:
  push:
    tags:
      - "v*.*.*" # déclenche sur un tag de version

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_HOME: /tmp/gpg-home
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Set provider name and version
        run: |
          PROVIDER_NAME=${GITHUB_REPOSITORY##*/}  # extrait juste le nom du repo
          VERSION=${GITHUB_REF_NAME#v}  # supprime le 'v' du début du tag
          echo "PROVIDER_NAME=$PROVIDER_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Provider: $PROVIDER_NAME, Version: $VERSION"

      - name: Build binaries
        run: |
          mkdir -p dist
          for os in linux darwin windows freebsd; do
            for arch in 386 amd64 arm arm64; do
              # Éviter certaines combinaisons non supportées par Go
              if [[ "$os" == "darwin" && ("$arch" == "386" || "$arch" == "arm") ]]; then
                continue
              fi
              echo "Building for $os/$arch"
              GOOS=$os GOARCH=$arch go build -o dist/${PROVIDER_NAME}_${VERSION}_${os}_${arch}
              zip dist/${PROVIDER_NAME}_${VERSION}_${os}_${arch}.zip dist/${PROVIDER_NAME}_${VERSION}_${os}_${arch}*
              rm dist/${PROVIDER_NAME}_${VERSION}_${os}_${arch}
            done
          done

      - name: Generate checksums
        run: |
          cd dist
          sha256sum *.zip > ${PROVIDER_NAME}_${VERSION}_SHA256SUMS

      - name: Setup GPG directory
        run: |
          mkdir -p "$GPG_HOME"
          chmod 700 "$GPG_HOME"

      - name: Import GPG key
        run: |
          export GNUPGHOME="$GPG_HOME"
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --list-secret-keys

      - name: Sign artifacts
        run: |
          export GNUPGHOME="$GPG_HOME"
          cd dist
          # Signer les fichiers zip (signature binaire, pas ASCII armored)
          for file in *.zip; do
            gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --detach-sign "$file"
          done
          # Signer le fichier SHASUMS (signature binaire, pas ASCII armored)
          gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --detach-sign "${PROVIDER_NAME}_${VERSION}_SHA256SUMS"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}