name: Release

on:
  push:
    tags:
      - "v*.*.*" # déclenche sur un tag de version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build binaries
        run: |
          mkdir -p dist
          for os in linux darwin windows; do
            for arch in amd64 arm64; do
              echo "Building for $os/$arch"
              GOOS=$os GOARCH=$arch go build -o dist/terraform-provider-windows_${os}_${arch}
              zip dist/terraform-provider-windows_${os}_${arch}.zip dist/terraform-provider-windows_${os}_${arch}*
              rm dist/terraform-provider-windows_${os}_${arch}
            done
          done

      - name: Generate checksums
        run: |
          cd dist
          sha256sum *.zip > SHA256SUMS

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --passphrase-fd 0 --import

      - name: Sign binaries
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          cd dist
          for f in *.zip; do
            gpg --batch --yes --detach-sign --armor --passphrase "$GPG_PASSPHRASE" "$f"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
